config/routes.rb
Rails.application.routes.draw do
  root :to => 'application#welcome'

  get '/universes/most_creatures' => 'universes#most_creatures'
  get '/travelers/most_wisdom' => 'travelers#most_wisdom'
  resources :travelers
  resources :universes do 
    resources :creatures
  end

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  post '/signout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'

  post '/creatures/collect' => 'creatures#collect'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/traveler.rb
class Traveler < ApplicationRecord
    has_secure_password
    has_many :traveler_universes
    has_many :traveler_creatures
    has_many :universes, through: :traveler_universes
    has_many :creatures, through: :traveler_creatures
    has_many :wisdoms, through: :creatures

    scope :most_wisdom, -> { joins(:traveler_creatures).group("traveler_creatures.traveler_id").order("count(traveler_creatures.traveler_id) desc").limit(1) }


    validates :username, uniqueness: true
    validates :username, presence: true

    def collect_wisdom(creature)
        self.creatures << creature 
    end

    def has_wisdom?(creature) 
        self.creatures.include?(creature) 
    end
end

app/controllers/travelers_controller.rb
class TravelersController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:new, :create]

    def most_wisdom
        @traveler = Traveler.most_wisdom.first
        render :most_wisdom
    end

    def new 
        @traveler = Traveler.new
    end 

    def create
        @traveler = Traveler.new(traveler_params)
        if @traveler.valid? 
            @traveler.save
            session[:traveler_id] = @traveler.id
            redirect_to traveler_path(@traveler)
        else
            render :new
        end
    end

    def show 
        set_traveler
        if session[:traveler_id] != @traveler.id 
            redirect_to :root
        else 
        end
    end

    def edit
        set_traveler
    end

    def update
        set_traveler
        if @traveler.update(traveler_params)
            redirect_to @traveler
        else
            render :edit
        end
    end
    
    def destroy
        set_traveler
        @traveler.destroy
        session.delete :traveler_id
        redirect_to :root
    end
     
    private
    
    def traveler_params
        params.require(:traveler).permit(:name, :uid, :username, :password, :password_confirmation)
    end

    def set_traveler
        @traveler = Traveler.find(params[:id])
    end
end

app/helpers/travelers_helper.rb
module TravelersHelper
end

app/views/travelers/_form.html.erb
<%= form_for(@traveler) do |f| %>
    <% if @traveler.errors.any? %>
      <div id="error_explanation">
        <h2>There were some errors:</h2>
  
        <ul>
          <% @traveler.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div><br>

    <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div><br>

    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div><br>

    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </div><br>
 
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/travelers/edit.html.erb
<h3>Editing <%= @traveler.name %></h3>

<%= render 'form' %>
<br>
<%= link_to 'Cancel and Return Home', @traveler %>

app/views/travelers/most_wisdom.html.erb
<h2>Wisest Traveler: <%= @traveler.name %>!</h2>
<p>
  Username: <%= @traveler.username %>
</p>


<br>
<p><%= link_to 'Go to Multiverse', universes_path %></p>

app/views/travelers/new.html.erb
<h3>Sign Up</h3>

<%= render 'form' %>

app/views/travelers/show.html.erb
<h2>Welcome, <%= @traveler.name %>!</h2>
<p>
  Username: <%= @traveler.username %>
</p>

<h3>Your wisdom collection: </h3>
<% @traveler.creatures.each do |creature| %>
  <p><i><%= creature.wisdom.words %></i></p>
  <p>  -  <%= link_to creature.name, universe_creature_path(creature.universe, creature) %></p>
<% end %>
<br>
<p><%= link_to 'Go to Multiverse', universes_path %></p>

<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='Sign Out'>
<% end %>
<br>
<%= link_to 'Edit Profile', edit_traveler_path(@traveler) %> | 
<%= link_to 'Delete Account', @traveler, method: :delete, data: { confirm: 'For real?' } %>