config/routes.rb
Rails.application.routes.draw do
  root :to => 'application#welcome'

  get '/universes/most_creatures' => 'universes#most_creatures'
  get '/travelers/most_wisdom' => 'travelers#most_wisdom'
  resources :travelers
  resources :universes do 
    resources :creatures
  end

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  post '/signout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create'

  post '/creatures/collect' => 'creatures#collect'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/universes_controller.rb
class UniversesController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: [:index, :show]

    def most_creatures
        @universe = Universe.most_creatures.first
        render :show
    end

    def index
        @universes = Universe.all
        @universe = Universe.new
    end
    
    def show
        set_universe
        respond_to do |format|
            format.html { render :show }
            format.json { render json: @universe }
        end
    end
    
    def new
        @universe = Universe.new
    end
    
    def edit
        set_universe
    end
    
    def create
        # @universe = Universe.create(universe_params)
        # render json: @universe, status: 201
        
        if @universe.save
            redirect_to @universe
        else
            render :new
        end
    end
    
    def update
        set_universe
        if @universe.update(universe_params)
            redirect_to @universe
        else
            render :edit
        end
    end
    
    def destroy
        set_universe
        @universe.destroy
        redirect_to universes_url
    end
    
    private
    
    def universe_params
        params.require(:universe).permit(
        :name, :description
        )
    end

    def set_universe 
        @universe = Universe.find_by(id: params[:id])
    end
end

app/helpers/universes_helper.rb
module UniversesHelper
end

app/views/universes/index.html.erb
<head>
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
</head> 

<h1>Universes</h1>

<div><%= link_to 'Create Universe', new_universe_path %></div>
<div><%= link_to 'View Universe with Most Creatures', universes_most_creatures_path %></div>

<br />

<% @universes.each do |universe| %>
    <h3><%= universe.name %></h3>
    <div id="universe-<%= universe.id %>">
    <button class="js-more" data-id="<%= universe.id %>">Learn More</button>
    </div>
    <br />
<% end %>

app/views/universes/new.html.erb
<div id="new-universe">
<h3>Create a Universe</h3>

<%= render 'form' %>
</div>

<%= link_to 'Back to Multiverse', universes_path %> | 

app/views/universes/show.html.erb
<h2><%= @universe.name %></h2>
<p>
  <%= @universe.description %>
</p>

<div id="creatures-list">
<button class="meet-creatures" data-id="<%= @universe.id %>">Meet Creatures</button>

</div>
<br>

<button class="sort-creatures" data-id="<%= @universe.id %>">Sort Creatures</button><br>


<%= link_to 'Back to Multiverse', universes_path %> | 
<%= link_to 'Edit', edit_universe_path(@universe) %> | 
<%= link_to 'Delete', @universe, method: :delete, data: { confirm: 'For real?' } %>